### ISSUE TITLE
'No such middleware to insert before'...

### ISSUE THREAD

**Issue by andreibosco** [nning/david#3]
I've created a new empty rails project, added david to the Gemfile and installed it, but when I try to start the project (`rails s`) I get the following error message:
```
/var/lib/gems/1.9.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:125:in 'asset_index': No such middleware to insert before: ActionDispatch::DebugExceptions (RuntimeError)
```

**Comment by nning** [comment]
Thanks for reporting this!

Someone else already reported this error via E-Mail but we couldn't find the cause, because we stopped debugging after the following sequence of commands worked:

    rails new dummy
    cd dummy
    echo "gem 'david'" >> Gemfile
    bundle
    rails s

Could you please try to reproduce that error with a new rails project and report the exact sequence of commands you ran?

**Comment by andreibosco** [comment]
Huh, those steps worked. Here's what I had done that caused the error:
```
rails new test
cd test
```
Edited `Gemfile` manually and inserted `gem 'david'` above `group :development`
```
bundle
rails s
```

When I put the gem declaration at the end of the Gemfile it works. Sorry for bothering :pensive:

**Comment by nning** [comment]
Great, thank you very much for your feedback; it's much appreciated!

With the help of your comment, I found out that the exception raises if the `web-console` gem is included and David is loaded before that, because David removes the (HTTP specific) `ActionDispatch::DebugExceptions` middleware by default and the `web-console` gem tries to insert itself into the middleware stack before `ActionDispatch::DebugExceptions` upon loading.

I see no real possibility to fix this in code. So I added a note about the removal of `web-console` to the README.md file if Rails/David is run in CoAP only mode in b840f75.

Thanks again!
