### ISSUE TITLE
Freezing with #NoMethodError using Rails 5.1.2 and coap.only = false

### ISSUE THREAD

**Issue by felixletkemann** [nning/david#4]
I am trying to use david in my Rails 5.1.2 application alongside a normal http output (user frontend, etc) to get this connected to some iot devices. 
Unfortunately, the application can not be used with http anymore after adding the david gem. First, I realized that http is simply disabled by the gem but I found the option coap.only = false. 
Now, instead of immediately not answering, the framework freezes with the error message:
```E, [2017-07-03T15:21:12.272780 #58268] ERROR -- : Couldn't cleanly terminate all actors in 2 seconds!
2017-07-03 15:21:12 +0200: Rack app error handling request { GET / }
#<NoMethodError: undefined method 'error' for nil:NilClass>
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/david-0.5.0/lib/david/show_exceptions.rb:31:in 'render_exception'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/david-0.5.0/lib/david/show_exceptions.rb:20:in 'rescue in _call'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/david-0.5.0/lib/david/show_exceptions.rb:12:in '_call'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/david-0.5.0/lib/david/show_exceptions.rb:8:in 'call'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:36:in 'call_app'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in 'block in call'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in 'block in tagged'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:26:in 'tagged'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in 'tagged'
/Users/felixletkemann/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in 'call'
```
My current configuration (application.rb) is: 

```
class Application < Rails::Application
  config.load_defaults 5.1
  config.coap.only = false
  config.coap.observe = false
  config.coap.log = :debug    
end
```

When the framework is frozen, I can stop it pressing Ctrl+C twice and I will get get the error message mentioned above. If I don't set the log level to :debug, I don't get anything. 
Reaching the CoAP routes using Firefox and Copper works just fine. So, I can use david for the intended purpose but it breaks the rest of the framework. 

Yours Sincerely, 
Felix

**Comment by felixletkemann** [comment]
Update: I previously said I can use the coap:// part with Firefox and Copper. I noticed that this is only true, if I set the gem to Coap only mode. If I set the CoAP only mode to false, Copper is repeating requests forever since it does not get any answers. 
So, I guess the issue does have something to do with the option coap.only.

**Comment by nning** [comment]
Hey,

thanks very much for reaching out!

Maybe the `coap.only` option is misleading or badly designed. When enabled – which it is by default – it starts David as default server when `rails s` (or `rackup`) is executed. It also removes some Rack middleware that is HTTP specific.

If it is set to `false`, `rails s` does not start an HTTP *and* CoAP server. The original Rack HTTP servers become default, again (puma, thin, webrick) and only a HTTP server is started.

When you want to run your application via HTTP and CoAP, you need two processes. If `coap.only` is set to `false`, you can start the CoAP server manually with `rails s coap` or `rails s david`.

However, I could reproduce the freezing bug both running on HTTP and CoAP. It seems to be caused by David since Rails 5, because the `David::ResourceDiscoveryProxy` Rack middleware was also inserted when the Rails app was running on HTTP only.

I fixed this in c94c369. Could you please check, if the master branch works for you, now?

Thanks again and best regards,
henning

**Comment by felixletkemann** [comment]
Thank your for your fast response, 
I thought I could use http and coap at the same time without trouble. Tomorrow I will check if your bugfix is working and give your some feedback. 

Beste Grüße, 
Felix

**Comment by nning** [comment]
Did it work?

**Comment by felixletkemann** [comment]
Sorry for not answering faster, 
I did not try out the solution yet since I already removed everything related to david from my rails project. Since I did not read your master thesis when I first tried out david, I thought it might be possible to use CoAP alongside HTTP (at the same time). 
Since this is not possible, I will use something much smaller than rails as an external "adapter application".
